<h1 align='center'> Twitter data extraction using tweepy

In [1]:
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener
import tweepy
import json
import pandas as pd
import csv
import re
from textblob import TextBlob
import string
import preprocessor as p
import os
import time

import numpy as np
import pandas as pd


import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [2]:
# Twitter credentials
# Obtain them from your twitter developer account
consumer_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
consumer_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
access_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
access_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
# Pass your twitter credentials to tweepy via its OAuthHandler
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_key, access_secret)
api = tweepy.API(auth)

In [7]:
#HappyEmoticons
emoticons_happy = set([
':-)', ':)', ';)', ':o)', ':]', ':3', ':c)', ':>', '=]', '8)',
'=)', ':}',
':^)', ':-D', ':D', '8-D', '8D', 'x-D', 'xD', 'X-D', 'XD', '=-D',
'=D',
'=-3', '=3', ':-))', ":'-)", ":')", ':*', ':^*', '>:P', ':-P',
':P', 'X-P',
'x-p', 'xp', 'XP', ':-p', ':p', '=p', ':-b', ':b', '>:)', '>;)',
'>:-)',
'<3'
])

In [8]:
# Sad Emoticons
emoticons_sad = set([
':L', ':-/', '>:/', ':S', '>:[', ':@', ':-(', ':[', ':-||', '=L',
':<',
':-[', ':-<', '=\\', '=/', '>:(', ':(', '>.<', ":'-(", ":'(",
':\\', ':-c',
':c', ':{', '>:\\', ';('
])

In [9]:
#Emoji patterns
emoji_pattern = re.compile("["
u"\U0001F600-\U0001F64F" # emoticons
u"\U0001F300-\U0001F5FF" # symbols & pictographs
u"\U0001F680-\U0001F6FF" # transport & map symbols
u"\U0001F1E0-\U0001F1FF" # flags (iOS)
u"\U00002702-\U000027B0"
u"\U000024C2-\U0001F251"
"]+", flags=re.UNICODE)

In [10]:
#combine sad and happy emoticons
emoticons = emoticons_happy.union(emoticons_sad)

#### Scrap tweets based on #Hashtag

In [7]:
def scraptweets(search_words, date_since, numTweets, numRuns):
    
    # Define a for-loop to generate tweets at regular intervals
    # We cannot make large API call in one go. Hence, let's try T times
    
    # Define a pandas dataframe to store the date:
    db_tweets = pd.DataFrame(columns = ['username','acctdesc','location','following','followers','totaltweets','usercreatedts',
                                        'tweetcreatedts','retweetcount','text','hashtags']
                                )
    program_start = time.time()
    for i in range(0, numRuns):
        # We will time how long it takes to scrape tweets for each run:
        start_run = time.time()
        
        # Collect tweets using the Cursor object
        # .Cursor() returns an object that you can iterate or loop over to access the data collected.
        # Each item in the iterator has various attributes that you can access to get information about each tweet
        tweets = tweepy.Cursor(api.search, q=search_words, lang="en", since=date_since, tweet_mode='extended').items(numTweets)
        # Store these tweets into a python list
        tweet_list = [tweet for tweet in tweets]
        # Obtain the following info (methods to call them out):
        # user.screen_name - twitter handle
        # user.description - description of account
        # user.location - where is he tweeting from
        # user.friends_count - no. of other users that user is following (following)
        # user.followers_count - no. of other users who are following this user (followers)
        # user.statuses_count - total tweets by user
        # user.created_at - when the user account was created
        # created_at - when the tweet was created
        # retweet_count - no. of retweets
        # (deprecated) user.favourites_count - probably total no. of tweets that is favourited by user
        # retweeted_status.full_text - full text of the tweet
        # tweet.entities['hashtags'] - hashtags in the tweet
        # Begin scraping the tweets individually:
        noTweets = 0
        for tweet in tweet_list:
        # Pull the values
            username = tweet.user.screen_name
            acctdesc = tweet.user.description
            location = tweet.user.location
            following = tweet.user.friends_count
            followers = tweet.user.followers_count
            totaltweets = tweet.user.statuses_count
            usercreatedts = tweet.user.created_at
            tweetcreatedts = tweet.created_at
            retweetcount = tweet.retweet_count
            hashtags = tweet.entities['hashtags']
            
            #Check for duplicate tweet:
            if username in db_tweets['username']:
                print("Found same username again, So checking the other features")
                i = db_tweets.loc[db_tweets['tweetcreatedts'] == tweetcreatedts].index[0]
                if retweetcount != db_tweets.at[i,'retweetcount'] or following != db_tweets.at[i,'following'] or followers != db_tweets.at[i,'followers']:
                    print("Features seems to be changed so updating it.")
                    db_tweets.at[i,'retweetcount'] = retweetcount
                    db_tweets.at[i,'following']    = following
                    db_tweets.at[i,'followers']    = followers
                continue
            
            
            try:
                text = tweet.retweeted_status.full_text
            except AttributeError:  # Not a Retweet
                text = tweet.full_text
            # Add the 11 variables to the empty list - ith_tweet:
            ith_tweet = [username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetcreatedts,retweetcount,
                         text,hashtags]
            # Append to dataframe - db_tweets
            db_tweets.loc[len(db_tweets)] = ith_tweet
            # increase counter - noTweets  
            noTweets += 1
        
        # Run ended:
        end_run = time.time()
        duration_run = round((end_run-start_run)/60, 2)
        
        print('no. of tweets scraped for run {} is {}'.format(i + 1, noTweets))
        print('time take for {} run to complete is {} mins'.format(i+1, duration_run))
        
        time.sleep(920) #15 minute sleep time
    # Once all runs have completed, save them to a single csv file:
    from datetime import datetime
    
    # Obtain timestamp in a readable format
    to_csv_timestamp = datetime.today().strftime('%Y%m%d_%H%M%S')
    # Define working path and filename
    filename = 'TestScrappedData.csv'
    # Store dataframe in csv with creation date timestamp
    db_tweets.to_csv(filename, index = False,encoding="utf-8")
    
    program_end = time.time()
    print('Scraping has completed!')
    print('Total time taken to scrap is {} minutes.'.format(round(program_end - program_start)/60, 2))

In [5]:
def clean_tweets(tweet):
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(tweet)
    #after tweepy preprocessing the colon symbol left remain after
    #removing mentions
    tweet = re.sub(r':', '', tweet)
    tweet = re.sub(r'‚Ä¶', '', tweet)
    #replace consecutive non-ASCII characters with a space
    tweet = re.sub(r'[^\x00-\x7F]+',' ', tweet)
    #remove emojis from tweet
    tweet = emoji_pattern.sub(r'', tweet)
    #filter using NLTK library append it to a string
    filtered_tweet = [w for w in word_tokens if not w in stop_words]
    filtered_tweet = []
    #looping through conditions
    for w in word_tokens:
    #check tokens against stop words , emoticons and punctuations
        if w not in stop_words and w not in emoticons and w not in string.punctuation:
            filtered_tweet.append(w)
    return ' '.join(filtered_tweet)

In [9]:
# Initialise these variables:
search_words = "#COVID19"
date_since = "2020-06-15"
numTweets = 500
numRuns = 1
# Call the function scraptweets
scraptweets(search_words, date_since, numTweets, numRuns)

no. of tweets scraped for run 1 is 500
time take for 1 run to complete is 0.5 mins
Scraping has completed!
Total time taken to scrap is 15.833333333333334 minutes.

In [3]:
tweets_df = pd.read_csv("TestScrappedData.csv")
tweets_df.head()

,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetcreatedts,retweetcount,text,hashtags
0,mrtallerjerry,NaN,NaN,75,1069,125041,2015-05-26 13:50:01,2020-06-19 09:37:40,1,Good point &amp; thx for reminder of book. No ...,[]
1,blessed_gist,businessman// blogger| alexxngetich@gmail.com,Konsa,119,186,4245,2013-11-25 12:49:25,2020-06-19 09:37:38,0,Sometimes we men hukatia madem just to see if ...,"[{'text': 'MUFC', 'indices': [97, 102]}, {'tex..."
2,milaniolivera,NaN,NaN,2795,1355,240859,2013-11-22 12:27:14,2020-06-19 09:37:38,1,.@EdConwaySky and @SajidJavid are hosting a ne...,"[{'text': 'TheWorldTomorrow', 'indices': [71, ..."
3,bacleague,Birmingham Ability Counts League 7V7 Pan Disab...,"Birmingham, England. BMRUFC",69,196,7419,2014-11-09 14:50:32,2020-06-19 09:37:38,19,The ONS has just published data on #COVID19 de...,"[{'text': 'COVID19', 'indices': [53, 61]}]"
4,KeithMillsD7,Dublin based Limerick man. Blocked by Gemma O...,"Limerick & Dublin, Ireland",3381,5197,82187,2007-05-23 18:53:50,2020-06-19 09:37:38,0,Northern Ireland seems to have joined the list...,"[{'text': 'COVID19', 'indices': [80, 88]}]"

In [11]:
tweets_df["Clean_Tweets"]=tweets_df.text.apply(clean_tweets)

In [12]:
tweets_df.head()

,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetcreatedts,retweetcount,text,hashtags,Clean_Tweets
0,mrtallerjerry,NaN,NaN,75,1069,125041,2015-05-26 13:50:01,2020-06-19 09:37:40,1,Good point &amp; thx for reminder of book. No ...,[],Good point amp thx reminder book No time reinv...
1,blessed_gist,businessman// blogger| alexxngetich@gmail.com,Konsa,119,186,4245,2013-11-25 12:49:25,2020-06-19 09:37:38,0,Sometimes we men hukatia madem just to see if ...,"[{'text': 'MUFC', 'indices': [97, 102]}, {'tex...",Sometimes men hukatia madem see tuko na hiyo k...
2,milaniolivera,NaN,NaN,2795,1355,240859,2013-11-22 12:27:14,2020-06-19 09:37:38,1,.@EdConwaySky and @SajidJavid are hosting a ne...,"[{'text': 'TheWorldTomorrow', 'indices': [71, ...",EdConwaySky SajidJavid hosting new podcast The...
3,bacleague,Birmingham Ability Counts League 7V7 Pan Disab...,"Birmingham, England. BMRUFC",69,196,7419,2014-11-09 14:50:32,2020-06-19 09:37:38,19,The ONS has just published data on #COVID19 de...,"[{'text': 'COVID19', 'indices': [53, 61]}]",The ONS published data COVID19 deaths disabili...
4,KeithMillsD7,Dublin based Limerick man. Blocked by Gemma O...,"Limerick & Dublin, Ireland",3381,5197,82187,2007-05-23 18:53:50,2020-06-19 09:37:38,0,Northern Ireland seems to have joined the list...,"[{'text': 'COVID19', 'indices': [80, 88]}]",Northern Ireland seems joined list countries c...

In [ ]:
# Tweets_DataFrame = pd.DataFrame(columns = ['username','acctdesc','location','following','followers','totaltweets','usercreatedts',
#                                         'tweetcreatedts','retweetcount','text','hashtags'])

In [ ]:
# def CheckForDuplicates(tweet_list):
#     #Check for duplicate tweet:
#     if tweet_list.username in Tweets_DataFrame['username'].values:
#         print(f"Found same username {tweet_list.username} again, So checking the other features")
#         if tweet_list.text not in Tweets_DataFrame['text'].values:
#             print("Tweets are not the same so Save it")
#             Tweets_DataFrame.loc[len(Tweets_DataFrame)] = tweet_list
#         else:
#             print("Tweets are same so ignore")
#     else:
#         Tweets_DataFrame.loc[len(Tweets_DataFrame)] = tweet_list

In [ ]:
# tweets_df.apply(CheckForDuplicates,axis=1)

In [55]:
Kholi_df = tweepy.Cursor(api.user_timeline, id="@imVkohli").items(10)

In [56]:
tweet_DT = [tweet for tweet in DTrump]

In [58]:
for K_tweet in Kholi_df:
    print(K_tweet.id)
    print(K_tweet.text)
    print(K_tweet.created_at)
    print("--------------------------------------------")

1273506293219594240
Great weather in Mumbai. Sitting out enjoying the beginning of my first proper experience of Mumbai monsoon. Couldn… https://t.co/Da3Shzm64P
2020-06-18 06:42:15
--------------------------------------------
1273115806067548162
Salute and deepest respect to the soldiers who sacrificed their lives to protect our country in the Galwan Valley.… https://t.co/kwARGZRZHv
2020-06-17 04:50:36
--------------------------------------------
1272116678579519488
Shocked to hear about Sushant Singh Rajput. This is so difficult to process. May his soul RIP and may god give all… https://t.co/nLoBAVY0LG
2020-06-14 10:40:25
--------------------------------------------
1271345549988335616
💭 https://t.co/e9spjDYkeG
2020-06-12 07:36:14
--------------------------------------------
1270996089198350338
Don't be scared to be wrogn. 👊 https://t.co/9rrWmDJynE
2020-06-11 08:27:36
--------------------------------------------
1269486988287070209
Caption this! 💭 https://t.co/YPBeTO5y2g
2020-06-07 04:30:58
--------------------------------------------
1269181240017477632
Wishing you a very Happy Birthday Jinx and a great year ahead. @ajinkyarahane88 🎂
2020-06-06 08:16:02
--------------------------------------------
1268174685205745664
Appalled to hear about what happened in Kerala. Let's treat our animals with love and bring an end to these cowardl… https://t.co/kkW6EAP2nB
2020-06-03 13:36:21
--------------------------------------------
1268063745227599872
RT @mybmc: DOs and DONTs for Mumbaikars to take on Cyclone Nisarga.

Dial 1916 and Press 4 for any cyclone related query or concern.

#BMCN…
2020-06-03 06:15:31
--------------------------------------------
1267397895889747968
RT @shyamsteel: Somethings are meant to be forever, be it your favourite dish, life partner or your home. Build your home with the #TMTBar…
2020-06-01 10:09:40
--------------------------------------------